// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";

export class CreateUserReducer
{
	public static call(_username: string)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _usernameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		serializer.write(_usernameType, _username);
			__SPACETIMEDB__.spacetimeDBClient.call("create_user", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let usernameType = AlgebraicType.createPrimitiveType(BuiltinType.Type.String);
		let usernameValue = AlgebraicValue.deserialize(usernameType, adapter.next())
		let username = usernameValue.asString();
		return [username];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:CreateUser", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("CreateUser", CreateUserReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("CreateUser", CreateUserReducer);
}

export default CreateUserReducer
