// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, IDatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, ReducerEvent } from "@clockworklabs/spacetimedb-sdk";
// @ts-ignore
import { StdbVector2 } from "./stdb_vector_2";

export class MoveUserViewReducer
{
	public static call(_loc: StdbVector2)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
		const serializer = __SPACETIMEDB__.spacetimeDBClient.getSerializer();
		let _locType = StdbVector2.getAlgebraicType();
		serializer.write(_locType, _loc);
			__SPACETIMEDB__.spacetimeDBClient.call("move_user_view", serializer);
		}
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let locType = StdbVector2.getAlgebraicType();
		let locValue = AlgebraicValue.deserialize(locType, adapter.next())
		let loc = StdbVector2.fromValue(locValue);
		return [loc];
	}

	public static on(callback: (reducerEvent: ReducerEvent, reducerArgs: any[]) => void)
	{
		if (__SPACETIMEDB__.spacetimeDBClient) {
			__SPACETIMEDB__.spacetimeDBClient.on("reducer:MoveUserView", callback);
		}
	}
}

__SPACETIMEDB__.reducers.set("MoveUserView", MoveUserViewReducer);
if (__SPACETIMEDB__.spacetimeDBClient) {
	__SPACETIMEDB__.spacetimeDBClient.registerReducer("MoveUserView", MoveUserViewReducer);
}

export default MoveUserViewReducer
