// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, IDatabaseTable, AlgebraicValue, ReducerEvent, Identity } from "@clockworklabs/spacetimedb-sdk";

export class SpawnableEntityComponent extends IDatabaseTable
{
	public static tableName = "SpawnableEntityComponent";
	public entityId: number;

	public static primaryKey: string | undefined = "entityId";

	constructor(entityId: number) {
	super();
		this.entityId = entityId;
	}

	public static serialize(value: SpawnableEntityComponent): object {
		return [
		value.entityId
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("entity_id", AlgebraicType.createPrimitiveType(BuiltinType.Type.U64)),
		]);
	}

	public static fromValue(value: AlgebraicValue): SpawnableEntityComponent
	{
		let productValue = value.asProductValue();
		let __entity_id = productValue.elements[0].asNumber();
		return new this(__entity_id);
	}

	public static count(): number
	{
		return __SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").count();
	}

	public static all(): SpawnableEntityComponent[]
	{
		return __SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").getInstances() as unknown as SpawnableEntityComponent[];
	}

	public static filterByEntityId(value: number): SpawnableEntityComponent | null
	{
		for(let instance of __SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").getInstances())
		{
			if (instance.entityId === value) {
				return instance;
			}
		}
		return null;
	}


	public static onInsert(callback: (value: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").onInsert(callback);
	}

	public static onUpdate(callback: (oldValue: SpawnableEntityComponent, newValue: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").onUpdate(callback);
	}

	public static onDelete(callback: (value: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").onDelete(callback);
	}

	public static removeOnInsert(callback: (value: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").removeOnInsert(callback);
	}

	public static removeOnUpdate(callback: (oldValue: SpawnableEntityComponent, newValue: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").removeOnUpdate(callback);
	}

	public static removeOnDelete(callback: (value: SpawnableEntityComponent, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("SpawnableEntityComponent").removeOnDelete(callback);
	}

}

export default SpawnableEntityComponent;

__SPACETIMEDB__.registerComponent("SpawnableEntityComponent", SpawnableEntityComponent);
