// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, IDatabaseTable, AlgebraicValue, ReducerEvent, Identity } from "@clockworklabs/spacetimedb-sdk";

export class UserComp extends IDatabaseTable
{
	public static tableName = "UserComp";
	public entityId: number;
	public identity: Identity;
	public username: string | null;
	public online: boolean;
	public timeLogin: number;
	public timeLogout: number | null;
	public timeRegister: number;

	public static primaryKey: string | undefined = "entityId";

	constructor(entityId: number, identity: Identity, username: string | null, online: boolean, timeLogin: number, timeLogout: number | null, timeRegister: number) {
	super();
		this.entityId = entityId;
		this.identity = identity;
		this.username = username;
		this.online = online;
		this.timeLogin = timeLogin;
		this.timeLogout = timeLogout;
		this.timeRegister = timeRegister;
	}

	public static serialize(value: UserComp): object {
		return [
		value.entityId, Array.from(value.identity.toUint8Array()), value.username ? { "some": value.username } : { "none": [] }, value.online, value.timeLogin, value.timeLogout ? { "some": value.timeLogout } : { "none": [] }, value.timeRegister
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("entity_id", AlgebraicType.createPrimitiveType(BuiltinType.Type.U64)),
			new ProductTypeElement("identity", AlgebraicType.createProductType([
			new ProductTypeElement("__identity_bytes", AlgebraicType.createArrayType(AlgebraicType.createPrimitiveType(BuiltinType.Type.U8))),
		])),
			new ProductTypeElement("username", AlgebraicType.createSumType([
			new SumTypeVariant("some", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new SumTypeVariant("none", AlgebraicType.createProductType([
		])),
		])),
			new ProductTypeElement("online", AlgebraicType.createPrimitiveType(BuiltinType.Type.Bool)),
			new ProductTypeElement("time_login", AlgebraicType.createPrimitiveType(BuiltinType.Type.U64)),
			new ProductTypeElement("time_logout", AlgebraicType.createSumType([
			new SumTypeVariant("some", AlgebraicType.createPrimitiveType(BuiltinType.Type.U64)),
			new SumTypeVariant("none", AlgebraicType.createProductType([
		])),
		])),
			new ProductTypeElement("time_register", AlgebraicType.createPrimitiveType(BuiltinType.Type.U64)),
		]);
	}

	public static fromValue(value: AlgebraicValue): UserComp
	{
		let productValue = value.asProductValue();
		let __entity_id = productValue.elements[0].asNumber();
		let __identity = new Identity(productValue.elements[1].asProductValue().elements[0].asBytes());
		let __username = productValue.elements[2].asSumValue().tag == 1 ? null : productValue.elements[2].asSumValue().value.asString();
		let __online = productValue.elements[3].asBoolean();
		let __time_login = productValue.elements[4].asNumber();
		let __time_logout = productValue.elements[5].asSumValue().tag == 1 ? null : productValue.elements[5].asSumValue().value.asNumber();
		let __time_register = productValue.elements[6].asNumber();
		return new this(__entity_id, __identity, __username, __online, __time_login, __time_logout, __time_register);
	}

	public static count(): number
	{
		return __SPACETIMEDB__.clientDB.getTable("UserComp").count();
	}

	public static all(): UserComp[]
	{
		return __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances() as unknown as UserComp[];
	}

	public static filterByEntityId(value: number): UserComp | null
	{
		for(let instance of __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances())
		{
			if (instance.entityId === value) {
				return instance;
			}
		}
		return null;
	}

	public static filterByIdentity(value: Identity): UserComp | null
	{
		for(let instance of __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances())
		{
			if (instance.identity.isEqual(value)) {
				return instance;
			}
		}
		return null;
	}

	public static filterByOnline(value: boolean): UserComp[]
	{
		let result: UserComp[] = [];
		for(let instance of __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances())
		{
			if (instance.online === value) {
				result.push(instance);
			}
		}
		return result;
	}

	public static filterByTimeLogin(value: number): UserComp[]
	{
		let result: UserComp[] = [];
		for(let instance of __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances())
		{
			if (instance.timeLogin === value) {
				result.push(instance);
			}
		}
		return result;
	}

	public static filterByTimeRegister(value: number): UserComp[]
	{
		let result: UserComp[] = [];
		for(let instance of __SPACETIMEDB__.clientDB.getTable("UserComp").getInstances())
		{
			if (instance.timeRegister === value) {
				result.push(instance);
			}
		}
		return result;
	}


	public static onInsert(callback: (value: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").onInsert(callback);
	}

	public static onUpdate(callback: (oldValue: UserComp, newValue: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").onUpdate(callback);
	}

	public static onDelete(callback: (value: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").onDelete(callback);
	}

	public static removeOnInsert(callback: (value: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").removeOnInsert(callback);
	}

	public static removeOnUpdate(callback: (oldValue: UserComp, newValue: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").removeOnUpdate(callback);
	}

	public static removeOnDelete(callback: (value: UserComp, reducerEvent: ReducerEvent | undefined) => void)
	{
		__SPACETIMEDB__.clientDB.getTable("UserComp").removeOnDelete(callback);
	}

}

export default UserComp;

__SPACETIMEDB__.registerComponent("UserComp", UserComp);
